services:
  - type: web
    name: mentha-api
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm run server
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
